## 📌 Como Executar  

Basta abrir o arquivo **index.html** em seu navegador e começar a jogar!  

---

🔗 **Sinta-se à vontade para contribuir com melhorias e sugestões!**  

by Vinicius Mafra, Curitiba - PR 